### ISSUE TITLE
Add basic authentication for the staging environment

### ISSUE THREAD

**Issue by philippkueng** [bitfondue/bitfondue-website#4]

**Comment by shringiishaan** [comment]
please describe your question

**Comment by philippkueng** [comment]
@shringiishaan it's not really a question but an item that needs to be done. Are you a bot or interested in the project?

**Comment by philippkueng** [comment]
As of https://github.com/bitfondue/bitfondue-website/commit/84ca04d8b0e6720225b15cb2c0e41d8e6d0d44e4 this issue is resolved.

**Comment by shringiishaan** [comment]
hey sorry i have been busy! I really havnt used Github, its my first time.
I'd be happy to work on a project, what can i do for you?
